spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    database: mysql


mybatis:
  mapper-locations: classpath:mapper/**.xml
  type-aliases-package: com.kyw.spring.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl